### ISSUE TITLE
Drop chrono, use std Time

### ISSUE THREAD

**Issue by 0xpr03** [Yoric/timer.rs#7]
It would be best to drop chrono and use std time, as chrono has some serious problems regarding conversion etc, you're kind of locked into the chrono universe as it is now.

**Comment by Yoric** [comment]
I have no real opinion on this. What are the problems with chrono, exactly? And is std::time powerful enough that we can get away with using just std::time?

**Comment by 0xpr03** [comment]
My main issue with chrono is it's golden cage, there issues open since a longer time regarding conversion from chrono time to the std time etc. It's brilliant in parsing etc, but can be a real pain if you have to get out of the normal chrono universe.
One big enhancement is also, that std::time won't be changed that much anymore, as it's now inside the std, breaking timer.rs less often.
As long as we're updating timer.rs accordingly it won't be a problem, otherwise it is.

**Comment by 0xpr03** [comment]
I'm closing this as chrono seems to do it's job and I'm against changing one of the essential input/ouput types of a working library if there's no hard fact why this would be required.
